using System;
using System.Collections.Generic;
using System.Text;

namespace RuneSharp.Enums.OsRs
{
    public enum OsrsMinigameName
    {
        BountyHunter,
        BountyHunterRogues,
        CastleWarGames,
        BarbarianAssultAttackers,
        BarbarianAssultDefenders,
        BarbarianAssultCollectors,
        BarbarianAssultHealers,
        DuelTournament,
        FistOfGuthix,
        HeistGuardLevel,
        HeistRobberLevel,
        ClueScrollBeginner,
        ClueScrollEasy,
        ClueScrollMedium,
        ClueScrollHard,
        ClueScrollAll,
        ClueScrollElite,
        ClueScrollMaster,
        BountyHunterRogue,
        BountyHunterHunter,
        LastManStanding,
        LeaugePoints,
        AbyssalSire,
        AlchemicalHydra,
        BarrowsChests,
        Bryophyta,
        Callisto,
        Cerberus,
        ChambersOfXeric,
        ChambersOfXericChallangeMode,
        ChaosElemental,
        ChaosFanatic,
        CommanderZilyana,
        CorporealBeast,
        CrazyArchaeologist,
        DagannothPrime,
        DagannothRex,
        DagannothSupreme,
        DerangedArchaeologist,
        GeneralGraador,
        GiantMole,
        GrotesqueGardians,
        Hespori,
        KalphiteQueen,
        KingBlackDragon, Kraken,
        KreeArra,
        KrillTsutsaroth,
        Mimic,
        Obor,
        Sarachnis,
        Scorpia,
        Skotizo,
        TheGauntlet,
        TheCorruptedGauntlet,
        TheatreOfBlood,
        ThermonuclearSmokeDevil,
        TzKalZuk,
        TzTokJad,
        Venenatis,
        Vetion,
        Vorkath,
        Wintertodt,
        Zalcano,
        Zulrah
    }
}
